from objects import objects
import math

def powerSwitch(master,masterlock,powerflag):
    """ Turns the 'power' boolean flag to parameter value. 'power' boolean flag is an attribute of the 'config' child of
    'master' data structure. 'Power' boolean flag is specifically used as a stop-and-go signal on time tracking and time-triggered events.
    parameters: (Master structure, Master lock, New value of 'power')"""
    masterlock.acquire()
    try:
        master.config.power = powerflag
        print("Turning simulation power to: "+str(master.config.power))
    finally:
        masterlock.release()

#TODO entire log tracking and recording of events should be handled on a specialized class.
def printLog(master,masterlock):
    """ Prints on console all tasks stored on the 'log' attribute of 'master' structure.
    parameters: (Master structure, Master lock)"""
    masterlock.acquire()
    try:
        print(str(master.log))
    finally:
        masterlock.release()


def getUserList(master,userlock):
    """ Returns an exact copy of the user list stored on 'master' structure on actual time.
    parameters: (Master structure, User lock)"""
    userlock.acquire()
    try:
        returnlist = master.user_list.copy()
    finally:
        userlock.release()
        return returnlist

def getPoiList(master,poilock):
    """ Returns an exact copy of the Point of interest list stored on 'master' structure on actual time.
    parameters: (Master structure, POI lock)"""
    poilock.acquire()
    try:
        returnlist = master.poi_list.copy()
    finally:
        poilock.release()
        return returnlist

def addUser(id, xpos, ypos, cache, speed, master, userlock):
    """ Inserts into 'master' structure's list of users a newly created user using data extracted from parameters.
    parameters: (User unique id, X position on canvas, Y position on canvas, Currently stored cache, Movement speed, 'Master' structure, User lock"""
    newuser = objects.User(int(id.get()), int(xpos.get()), int(ypos.get()), cache, speed)
    print(newuser.__dict__)
    userlock.acquire()
    try:
        master.user_list.append(newuser)
    finally:
        userlock.release()

def addPoi(id, xpos, ypos, category, master, poilock):
    """ Inserts into 'master' structure's list of POIs a newly created POI using data extracted from parameters.
    parameters: (POI unique id, X position on canvas, Y position on canvas, POI semantic category, 'Master' structure, POI lock)"""
    newpoi = objects.Poi(int(id.get()), int(xpos.get()), int(ypos.get()), category)
    print(newpoi.__dict__)
    poilock.acquire()
    try:
        master.poi_list.append(newpoi)
    finally:
        poilock.release()

#TODO in addUser(): Validate x and y within canvas borders, Validate id as a unique value.

def removeUser(id,master,userlock):
    """ Given an id, this function removes an specific User from the 'master' structure's list of users.
    parameters: (User ID, 'master' structure, User lock)"""
    userlock.acquire()
    try:
        for element in master.user_list:
            if element.id == id:
                master.user_list.remove(element)
    finally:
        userlock.release()

def toggleGrid(master, masterlock, flag):
    """ This function toggles 'showGrid' boolean flag stored on 'master.config' (see objects.py on objects package)
    structure to True or False depending on 'flag' value extracted from a BooleanVar() generated by tkinter.
    These variables return either 0 or 1 when readed, so it's interpretated by the function before changing the
    'master.config' flag accordingly."""
    if flag == 1:
        toggleflag = True
    elif flag == 0:
        toggleflag = False
    elif flag != 0 and flag != 1:
        print("Wrong grid parameter.")
        return
    masterlock.acquire()
    try:
        master.config.showGrid = toggleflag
    finally:
        masterlock.release()




#Validations!

def checkEntryDataType(idinput, xinput, yinput):
    """This function checks that every parameter included it's numeric and returns True. If it's not returns False."""
    returnFlag = True
    if not (idinput.get().isnumeric()):
        returnFlag = False
    if not (xinput.get().isnumeric()):
        returnFlag = False
    if not (yinput.get().isnumeric()):
        returnFlag = False
    return returnFlag


def checkUserUnique(idinput, master, userlock):
    """This function checks if given ID doesn't exist within the Users list population. If exists returns false, if it's not, returns true."""
    userlock.acquire()
    try:
        returnFlag = True
        for element in master.user_list:
            if (int(idinput.get()) == element.id):
                returnFlag = False
    finally:
        userlock.release()
        return returnFlag

def checkPoiUnique(idinput, master, poilock):
    """This function checks if given ID doesn't exist within the POI list population. If exists returns false, if it's not, returns true."""
    poilock.acquire()
    try:
        returnFlag = True
        for element in master.poi_list:
            if (int(idinput.get()) == element.id):
                returnFlag = False
    finally:
        poilock.release()
        return returnFlag


def checkBoundariesOnCanvas(xinput, yinput, master, masterlock):
    """This function gets X and Y input values from parameters and check if they exists within Canvas border stated on 'master' structure."""
    returnFlag = True
    masterlock.acquire()
    try:
        canvasx = master.canvas[0]
        canvasy = master.canvas[1]
    finally:
        masterlock.release()
        if not (int(xinput.get()) > 0 and int(xinput.get()) < canvasx):
            returnFlag = False
        if not (int(yinput.get()) > 0 and int(yinput.get()) < canvasy):
            returnFlag = False
        return returnFlag

def checkCategorySelected(category):
    """This function checks if parameter is within possible POI semantic category limit which is now 5"""
    if (category >= 0 and category <= 5):
        return True
    else:
        return False
